### PR TITLE
1. Split Ht_AFE_ABC into sub modules

### PR DESCRIPTION
**Pull request by sujitnair**
2. Wrote unittests for each

### CODE REVIEW

**Comment by sujitnair** [comment]
@km-git-acc @dhjpolymath 

I need **both** of you have a look at this and give a thumbs up if it looks good?

**Comment by km-git-acc** [comment]
I am ok with this. It does make things neater. The reason I had just made one function was that A, B, C have potentially some common terms hence there could be some elimination of redundant calculations (which I later didnt go much into except the C_pre1 factor), and Terry had mentioned in the blog that we can tinker with N and M values a bit (which I was planning to but again didnt go much into :)

**Comment by sujitnair** [comment]
Yeah, splitting into modules makes code maintenance easier with the right unit tests.

It will also enable more sanity checks. For example, B should dominate A when y >> 1/log(x).

**Comment by sujitnair** [comment]
@dhjpolymath You ok with this?

**Comment by km-git-acc** [comment]
I guess lets wait for a day more. If the output with the previous Ht_AFE_ABC implementation and the new one is exactly matching (will just do a sanity check within a small z range myself), we should have no problems in merging.

**Comment by sujitnair** [comment]
Thanks. And please add the values you find during the sanity check to 
dbn_upper_bound/tests/python/test_rz.py

That way, we can catch a subset of bugs when we run unit tests before merges. The values in test_rz.py becomes the "ground truth" moving forward.

**Comment by km-git-acc** [comment]
So i checked it for a few values, and it checks out. Added two of those values to test_ht.py.
Merging this into the main branch.


t | z | Ht_old | Ht_new
-- | -- | -- | --
0.23 | 1000000 | -2.079117127359716401705367663903184175629392964318676288277755004089816901327445854856268904159123038e-170537 | -2.079117127359716401705367663903184175629392964318676288277755004089816901327445854856268904159123038e-170537
0.23 | 1500000 | 6.306238093436803707549741808430831191336887654024911614570585844136774150547359675859058593249360643e-255811 | 6.306238093436803707549741808430831191336887654024911614570585844136774150547359675859058593249360643e-255811
0.23 | 2000000 | 5.525414492567568702110709740136630790574237567188208395285453647201216371487215095173547913663581248e-341084 | 5.525414492567568702110709740136630790574237567188208395285453647201216371487215095173547913663581248e-341084
0.23 | 2500000 | -1.816197341210199373890988404117565512072197227408257731202331183395383722483023738008023981345123953e-426357 | -1.816197341210199373890988404117565512072197227408257731202331183395383722483023738008023981345123953e-426357
0.23 | 3000000 | 7.754307373196585578741651057258108684598351023017606312425048617731234941784349947001564214588866919e-511631 | 7.754307373196585578741651057258108684598351023017606312425048617731234941784349947001564214588866919e-511631
0.23 | 3500000 | -4.311333384344234227627604932617747645321916443758447785339793533731755841452739059911057185076735304e-596904 | -4.311333384344234227627604932617747645321916443758447785339793533731755841452739059911057185076735304e-596904
0.23 | 4000000 | 1.849346581857595290828388175185602772605977510366837156300952799617474188924307949526243973513078996e-682177 | 1.849346581857595290828388175185602772605977510366837156300952799617474188924307949526243973513078996e-682177
0.23 | 4500000 | -5.461762576726077175538368993064590560199942435570382949545856676587306362377239619743619514192411523e-767452 | -5.461762576726077175538368993064590560199942435570382949545856676587306362377239619743619514192411523e-767452
0.23 | 5000000 | -3.724483728717267684027584930204154527425444773620691707476003021671721866798300535779239796952892495e-852724 | -3.724483728717267684027584930204154527425444773620691707476003021671721866798300535779239796952892495e-852724
0.23 | 5500000 | 4.762779138146087224928085899631867385099078635548556458230222000396281878974737921953362820492297311e-937998 | 4.762779138146087224928085899631867385099078635548556458230222000396281878974737921953362820492297311e-937998
0.23 | 6000000 | 2.269082369066877693404463241315007965699312116462579387872863768049826124253261699385501482539756863e-1023271 | 2.269082369066877693404463241315007965699312116462579387872863768049826124253261699385501482539756863e-1023271
0.23 | 6500000 | -9.421761942364770038918803326187976509108813383817165273622122284219873135648449632058521607353327142e-1108545 | -9.421761942364770038918803326187976509108813383817165273622122284219873135648449632058521607353327142e-1108545
0.23 | 7000000 | -3.432416812491576600135222339366648177578346924402727879306061072058711885271427848080674419878049477e-1193818 | -3.432416812491576600135222339366648177578346924402727879306061072058711885271427848080674419878049477e-1193818
0.23 | 7500000 | -8.044533113882313194578664226069778712878414513514697559919113606135053906571072838949985259609896719e-1279093 | -8.044533113882313194578664226069778712878414513514697559919113606135053906571072838949985259609896719e-1279093
0.23 | 8000000 | 4.542665042669135215038308478560259023143154078520441486023217331690730142958256152261402018201406145e-1364365 | 4.542665042669135215038308478560259023143154078520441486023217331690730142958256152261402018201406145e-1364365
0.23 | 8500000 | 8.221577174316981864874717716500140779048045274845883897332717032100195489203685934352452716725274696e-1449639 | 8.221577174316981864874717716500140779048045274845883897332717032100195489203685934352452716725274696e-1449639
0.23 | 9000000 | 7.952386689564758470933522131290403906379673882398369186584685650820385935577826016489459335590518074e-1534912 | 7.952386689564758470933522131290403906379673882398369186584685650820385935577826016489459335590518074e-1534912
0.23 | 9500000 | 4.228236383248905761701707872898031630648561605389317106651788749556255090308573312221754118412998559e-1620186 | 4.228236383248905761701707872898031630648561605389317106651788749556255090308573312221754118412998559e-1620186
0.23 | 10000000 | 1.825621217943237998812425234863332498990749762203623357684483167319632091079653942070743289989033176e-1705458 | 1.825621217943237998812425234863332498990749762203623357684483167319632091079653942070743289989033176e-1705458

**Comment by mariotrevi** [comment]
@KM, @SujitNair,


On 02/10/2018 07:25 AM, KM wrote:
>
> So i checked it for a few values, and it checks out. Added two of 
> those values to test_ht.py.
> Merging this into the main branch.
>
> t 	z 	Ht_old 	Ht_new
> 0.23 	1000000 	-2.079117127359716401705367663903184175 [...] 
> 856268904159123038e-170537
>

I think I'll try H_{0.23} (1,000,000) using Gauss-Legendre, but
experimenting in PARI/gp ....

David

**Comment by sujitnair** [comment]
@km-git-acc Please run

python -m unittest

**before** any PR or merge. The unittest is failing :(

**Pull request merged**
