### PR TITLE
Adding the more accurate H_t AFE eqn - Ht_AFE_ABC

### PR DESCRIPTION
**Pull request by km-git-acc**
Added the new more accurate approx functional eqn Ht_AFE_ABC
as derived by Terry at 
https://terrytao.wordpress.com/2018/02/02/polymath15-second-thread-generalising-the-riemann-siegel-approximate-functional-equation/#comment-492182

The C term was changed according to later comments, and since it is showing good results.

### CODE REVIEW

**Comment by km-git-acc** [comment]
@sujitnair I realized you had mentioned about sending the pull request directly to you. How do we do that?

**Comment by sujitnair** [comment]
@km-git-acc You should be able to assign it to me from the top right on this page (Reviewers).

**Comment by sujitnair** [comment]
Also, can you run pylint on this (or at least for Ht_AFE_ABC) and ping me? It will make the code easier to read and debug down the line.

The details are in CONTRIBUTING.md

**Comment by km-git-acc** [comment]
So I ran Ht_AFE_ABC and psi functions through some online check http://pep8online.com/checkresult
and it gives me this result

Code | Line | Column | Text
-- | -- | -- | --
E302 | 8 | 1 | expected 2 blank lines, found 1
E231 | 8 | 17 | missing whitespace after ','
W291 | 9 | 75 | trailing whitespace
E231 | 12 | 6 | missing whitespace after ','
E231 | 12 | 20 | missing whitespace after ','
E231 | 18 | 44 | missing whitespace after ','
E231 | 20 | 21 | missing whitespace after ','
E225 | 21 | 13 | missing whitespace around operator
E701 | 21 | 16 | multiple statements on one line (colon)
E231 | 21 | 79 | missing whitespace after ','
E501 | 21 | 80 | line too long (96 > 79 characters)
E231 | 21 | 94 | missing whitespace after ','
E701 | 22 | 13 | multiple statements on one line (colon)
E231 | 22 | 36 | missing whitespace after ','
W291 | 22 | 39 | trailing whitespace
E231 | 25 | 44 | missing whitespace after ','
E231 | 27 | 21 | missing whitespace after ','
E225 | 28 | 13 | missing whitespace around operator
E701 | 28 | 16 | multiple statements on one line (colon)
E231 | 28 | 79 | missing whitespace after ','
E501 | 28 | 80 | line too long (98 > 79 characters)
E231 | 28 | 94 | missing whitespace after ','
E701 | 29 | 13 | multiple statements on one line (colon)
E231 | 29 | 36 | missing whitespace after ','
W291 | 29 | 41 | trailing whitespace
E231 | 34 | 35 | missing whitespace after ','
E225 | 39 | 14 | missing whitespace around operator
E701 | 39 | 17 | multiple statements on one line (colon)
E701 | 40 | 9 | multiple statements on one line (colon)

it seems to be a modern day grammar teacher :)

**Comment by km-git-acc** [comment]
But I understand standardization will help a lot down the road. 
Have also used the latest sample_afe_calc.py to create sample_afe_abc_calc.py
It uses the new eqn for large scale computation, and now also finds the exact root in the interesting intervals instead of relying only on the midpoint estimate.

main readme has also been updated to reflect this.

**Comment by sujitnair** [comment]
Lol at "grammar teacher" :)

I am not sure how much the pep8 matches our project pylintrc file. So you will have to use pylint locally.

Yeah, standardization helps a lot as more people get involved. Right now it is just you and me mostly.

**Comment by km-git-acc** [comment]
@sujitnair Will look into pylint from mext time. Just saw that @dhjpolymath has started some new computations using the older approx func eqn when the new preferred one is available in the pull request, so to avoid confusion I am merging this into master.

**Comment by sujitnair** [comment]
Sounds good. We should also delete old files/functions to avoid confusion.

**Comment by km-git-acc** [comment]
Yeah, I will try to clean it up a bit tomorrow. Currently deleting the other branches, since all the important parts have been taken. Looking at the python folder in master, these seem to be the important files (apart from init)
utility.py, mputility.py, constants.py,  sample_afe_abc_calc.py, first_1000_zeta.py

sample_afe_calc.py and Ht_real_compute can be removed. Other files  starting with Ht_ can be moved to some 'older files' folder in case someone still wants to use them. What do you think?

**Comment by sujitnair** [comment]
I prefer just to remove them as long as our README.md is updated. 

One can always recover those files (if needed) from the GitHub commit history/logs.

**Pull request merged**
