### PR TITLE
Habb bound

### PR DESCRIPTION
**Pull request by km-git-acc**
Added a new file in the research folder. Since it is not dependent on any other file, there are no conflicts as of now and merging it.

### CODE REVIEW

**Comment by km-git-acc** [comment]
Also added a table in the research folder with values of normalized E1 and E2 for every N.

**Comment by rudolph-git-acc** [comment]
@km-git-acc

The Wiki-displays for: 

  sNminus = 0.5*(1-y + 0.5j*(xN+xNp1))
  sNplus = 0.5*(1+y + 0.5j*(xN+xNp1))

seem ambiguous. For SNplus there is the extra divide by 2 of the imaginary part but it isn't there for SNminus. The overall impact is quite small, but with my Pari/gp code, I get for N=3 without the extra divide by 2 : 
E1b = 0.011899755286837463526
E2b = 0.015437919799843511060 

and with the extra divide I do get exactly your numbers from the csv-file.

Do you know which display is the correct one?

**Comment by km-git-acc** [comment]
@rudolph-git-acc 

Ok, I went through the wiki again and noticed the difference. If we go through the derivation laid out by Prof. Tao, it seems the extra divide is required. (x_N + x_N+1)/2 is the average x value for the N interval, and the alpha1'(s) upper bound seems to be obtained for x values between the desired x and this average. If the division did not take, the imaginary part of the numerator would fall in the next N interval.
But it would be better to ask him to be certain.

**Comment by km-git-acc** [comment]
@rudolph-git-acc 

Also, I think he had recently mentioned that Re(alpha1(s)) should behave similarly to log(N). In fact, in http://michaelnielsen.org/polymath1/index.php?title=Controlling_A%2BB/B_0#Analysing_the_effective_model
one of the major differences in the toy model vs the effective model is that logN gets replaced by Re(alpha1(s))

If we compare Re(alpha1(sn)) where the imaginary numerator is (xN+xNp1)/2, with logN for different values of N, we do see they are very similar (in the sn derivation, there is also a K factor, but that is much smaller compared to Re(alpha1(sn))).


N | logN | Re(alpha1((1+y+(xN+xNp1)/2)/2)) | diff
-- | -- | -- | --
28 | 3.33 | 3.35 | 0.02
39 | 3.66 | 3.68 | 0.01
48 | 3.87 | 3.88 | 0.01
56 | 4.03 | 4.03 | 0.01
63 | 4.14 | 4.15 | 0.01
69 | 4.23 | 4.24 | 0.01
74 | 4.30 | 4.31 | 0.01
79 | 4.37 | 4.38 | 0.01
84 | 4.43 | 4.44 | 0.01
89 | 4.49 | 4.49 | 0.01

On the other hand, if we use (xN+xNp1) as the imaginary numerator, we get 

N | logN | Re(alpha1((1+y+(xN+xNp1))/2)) | diff
-- | -- | -- | --
28 | 3.33 | 3.70 | 0.36
39 | 3.66 | 4.02 | 0.36
48 | 3.87 | 4.23 | 0.36
56 | 4.03 | 4.38 | 0.36
63 | 4.14 | 4.50 | 0.35
69 | 4.23 | 4.59 | 0.35
74 | 4.30 | 4.66 | 0.35
79 | 4.37 | 4.72 | 0.35
84 | 4.43 | 4.78 | 0.35
89 | 4.49 | 4.84 | 0.35

In this case, the diff remains significant.

**Pull request merged**
